default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: test2dbs
  password: p-secret
  port: 5433

development:
  primary:
    <<: *default
    database: test2dbs_development
  other:
    <<: *default
    database: test2dbs_other_development
    migrations_paths: db/migrate_other

test:
  primary:
    <<: *default
    database: test2dbs_test
  other:
    <<: *default
    database: test2dbs_other_test
    migrations_paths: db/migrate_other
